openapi: "3.0.0"
info:
  version: 0.4.0
  title: swagger test
  description: It's my first swagger practice
  license:
    name: MIT
servers:
  - url: http://localhost:5000/
tags:
  - name: user
  - description: User API 입니다.
paths:
  /api/users/register:
    $ref: "./paths/user.yaml#/~1api~1users~1register"
  /api/users/login:
    $ref: "./paths/user.yaml#/~1api~1users~1login"
  /api/users/withdrawal:
    $ref: "./paths/user.yaml#/~1api~1users~1withdrawal"
  /api/users/passwordInitialization:
    $ref: "./paths/user.yaml#/~1api~1users~1passwordInitialization"
components:
  schemas:
    User:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          format: email
        password:
          type: string
        name:
          type: string
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
  responses:
    successResponse:
      description: successful request
      content:
        application/json:
          schema:
            type: object
            properties:
              email: test@test.com
              password: 1234
    BadRequest:
      description: bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
